### PR TITLE
mention PET up top

### PR DESCRIPTION
**Pull request by JeffFessler**
Just learned about this package from Kris and I am excited to see 3D TOF PET here!
Seems like it is worth mentioning "PET" somewhere in the top of the readme?
(Unless this package also works for X-ray CT and SPECT?)

BTW,  do the defaults in class `RegularPolygonPETScanner` correspond to some particular PET scanner model?  If so, it would be nice to say which one to help orient people.

### CODE REVIEW

**Comment by gschramm** [comment]
(1) Thanks for the encouraging feedback. The aim of the package is to provide flexible non-TOF and OTF projectors optimized for CUDA and OpenMP (so far only the Joseph projector). So in principle these projectors can be used for X-ray and SPECT as well.
But since I am mostly working on PET, the high level python examples are bit biased towards PET.

(2)  The default settings in ```RegularPolygonPETScanner``` roughly correspond to the geometry of the GE SIGNA. But I would prefer to keep things "vendor-neutral".

**Comment by JeffFessler** [comment]
SPECT requires collimator response modeling, which is very different than Joseph projector or its relatives.  CT requires cone-beam geometry - if that geometry is supported somewhere then it would be great to mention that in the README.

**Comment by gschramm** [comment]
Very true of course. The projectors are setup in a way that they take a list of start and end points and calculate line integrals between them (according to Joseph). So far I didn't implement any advanced methods of resolution modeling, but that might come in the future.

I will update the README accordingly.

**Comment by gschramm** [comment]
The README was updated in 6ee4c60 and I also update the installation instructions in 113e7b440. I am always happy to help and get feedback in case you or someone of your group wants to give it a try.

**Pull request closed without merging**
